Check for man pages to exist before making a tarball
Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@gmail.com>

diff --git a/tools/Makefile.am b/tools/Makefile.am
--- a/tools/Makefile.am
+++ b/tools/Makefile.am
@@ -42,3 +42,12 @@ dist_man_MANS = $(man_pages)
 CLEANFILES = $(dist_man_MANS)
 MAINTAINERCLEANFILES = $(man_pages) *.xml
 endif
+
+# make sure manpages were built before running dist
+dist-hook:
+	@test -f $(distdir)/evemu-describe.1 || (\
+		echo "******************************************************" && \
+		echo "Couldn't find man pages, refusing make dist." && \
+		echo "Install xmlto/asciidoc to build man pages for tarball." && \
+		echo "******************************************************" && \
+		test )
